name: tim_push
description: "Tencent Cloud TIMPush Flutter plugin with Android/iOS/OHOS support."
version: 1.2.1
repository: https://github.com/lm83680/tim_push
issue_tracker: https://github.com/lm83680/tim_push/issues
topics:
  - tim
  - push
  - notification

environment:
  sdk: ^3.6.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.plugin.tim_push
        pluginClass: TimPushPlugin
      ios:
        pluginClass: TimPushPlugin
      ohos:
        package: com.plugin.tim_push
        pluginClass: TimPushPlugin
